[
   {
      "alumno":"Pedro",
      "nota":7.09,
      "ranking":10
   },
   {
      "alumno":"Juan",
      "nota":4,
      "ranking":150
   },
   {
      "alumno":"Lucía",
      "nota":9.5,
      "ranking":5
   },
   {
      "alumno":"Erika",
      "nota":7.75,
      "ranking":24
   },
   {
      "alumno":"Sofía",
      "nota":9,
      "ranking":100
   },
   {
      "alumno":"Enrique",
      "nota":6,
      "ranking":210
   },
   {
      "alumno":"Anabel",
      "nota":2.5,
      "ranking":34
   },
   {
      "alumno":"Xavier",
      "nota":5.2,
      "ranking":13
   },
   {
      "alumno":"Álvaro",
      "nota":10,
      "ranking":1
   },
   {
      "alumno":"Gemma",
      "nota":7.94,
      "ranking":7
   }
]